### ISSUE TITLE
Quickstart example does not work

### ISSUE THREAD

**Issue by simeoncarstens** [pepkit/pipestat#153]
The quickstart example on https://pep.databio.org/pipestat/ does not work. After installing `pipestat` in a virtual environment, setting the environment variables and creating the `output_schema.yaml` file, running `pipestat report -i result_name -v 1.1` makes `pipestat` yell at me:
```console
$ pipestat report -i result_name -v 1.1
Could not locate config file.
Traceback (most recent call last):
  File "/home/simeon/projects/uva/pipestat/.venv/bin/pipestat", line 8, in <module>
    sys.exit(main())
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/cli.py", line 113, in main
    psm = PipestatManager(
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 175, in __init__
    self.process_schema(schema_path)
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 499, in process_schema
    parsed_schema = ParsedSchema(schema_to_read)
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/parsed_schema.py", line 140, in __init__
    raise SchemaError(
pipestat.exceptions.SchemaError: Could not find valid pipeline identifier (key 'pipeline_name') in given schema data
```
If I then add the following line:
```yaml
pipeline_name: "my_pipeline"
```
to `output_schema.yaml`, this particular problem seems to be solved, but it then throws another error:
```console
Could not locate config file.
Traceback (most recent call last):
  File "/home/simeon/projects/uva/pipestat/.venv/bin/pipestat", line 8, in <module>
    sys.exit(main())
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/cli.py", line 113, in main
    psm = PipestatManager(
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 175, in __init__
    self.process_schema(schema_path)
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 499, in process_schema
    parsed_schema = ParsedSchema(schema_to_read)
  File "/home/simeon/projects/uva/pipestat/.venv/lib/python3.10/site-packages/pipestat/parsed_schema.py", line 146, in __init__
    raise SchemaError("Neither sample-level nor project-level data items are declared.")
pipestat.exceptions.SchemaError: Neither sample-level nor project-level data items are declared.
```
at which point I gave up.
So I guess this example would need to be updated :slightly_smiling_face:

**Comment by donaldcampbelljr** [comment]
Thanks for flagging this. I've merged the changes to dev!
