### ISSUE TITLE
OSError: Could not make this path absolute

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#7]
```
pipestat report -i myval -v 123 -n test -f test.yaml
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/pipestat", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/cli.py", line 28, in main
    psm = PipestatManager(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/pipestat.py", line 198, in __init__
    results_file_path = _mk_abs_via_cfg(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/pipestat.py", line 96, in _mk_abs_via_cfg
    raise OSError(f"Could not make this path absolute: {path}")
OSError: Could not make this path absolute: test.yaml
```

It's unclear to me why it wouldn't make that path absolute.

**Comment by nsheff** [comment]
This is what happens when the file doesn't exist. I changed the error message accordingly.

But why can't it write it to a new results file, even if it doesn't exist? In other words, if the results file doesn't exist, it should be created, instead of giving an error.
