### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/pipestat#91]
Pipestat imports jinja2, but the dependency isn't defined in requirements.txt, therefore using packages that depend on pipestat results in `ModuleNotFoundError`.

For example refgenie (directly depends on pypiper, which depends on pipestat): 
```
refgenie --help
Traceback (most recent call last):
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/bin/refgenie", line 5, in <module>
    from refgenie.__main__ import main
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/refgenie/__main__.py", line 3, in <module>
    from .cli import main
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/refgenie/cli.py", line 22, in <module>
    from .argparser import build_argparser
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/refgenie/argparser.py", line 3, in <module>
    import pypiper
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pypiper/__init__.py", line 6, in <module>
    from .manager import *
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pypiper/manager.py", line 32, in <module>
    from pipestat import PipestatError, PipestatManager
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pipestat/__init__.py", line 8, in <module>
    from .pipestat import *
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pipestat/pipestat.py", line 14, in <module>
    from .html_reports_pipestat import HTMLReportBuilder, fetch_pipeline_results
  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pipestat/html_reports_pipestat.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```

I installed refgenie@latest in a fresh virtualenv.

**Comment by nsheff** [comment]
hmm, I can't remember -- why does pipestat need `jinja2`? I guess for the report building functionality...

**Comment by stolarczyk** [comment]
I think you're right. That's the last line from the error traceback:


  File "/Users/stolarczyk/Library/Caches/pypoetry/virtualenvs/refgenie-test-A0KxTI2w-py3.10/lib/python3.10/site-packages/pipestat/**html_reports_pipestat.py**", line 9, in <module>
    **import jinja2**
